### ISSUE TITLE
Hi, looking at video

### ISSUE THREAD

**Issue by hadaev8** [forcecore/Keras-GAN-Animeface-Character#1]
How many frames in second?
http://puu.sh/yrZJ6/5c748086e0.png
Geting this on 3050 x32 mini batch, its ok or color noise should gone?

**Comment by forcecore** [comment]
I think it was 25 fps. I rendered one frame per 10 mini-batches.
5000 mini-batches / 10 = 500 frames.
500 frames / 25 frames-per-second = 20 seconds, which is the length of the Youtube video.

I think you have too much noise and the networks are not learning anything. It could be caused by anything, even the default learning parameters in your deep learning framework could be the cause.

**Comment by hadaev8** [comment]
Don't know, I copied your architecture, hyperparameters and dataset, but can't make it work.
In the best case get big blotches of color.
I tried to do encoder, it works (probably, get сhan with mixed colors).

Maybe I'm missing something obvious
https://pastebin.com/Kc152eG8

**Comment by hadaev8** [comment]
Lol, all this time i had broken output to pic file.
Thanks for great code and usefull links.
